### ISSUE TITLE
Проверка (валидация) ключа 

### ISSUE THREAD

**Issue by seredniy** [mdenisenko/woo-nova-poshta#1]
![image](https://user-images.githubusercontent.com/11270429/77361725-7d012c80-6d58-11ea-92db-f3c66d6b024d.png)

Очень удобно, когда после ввода ключа и телефона, снизу появляется надпись типа "ключ рабочий, все хорошо". А то ввел и не понимашь правильно или нет

**Comment by mdenisenko** [comment]
Будет добавлена проверка при сохранении настроек
